#' @name adapt_ISMCMC
#' @title Independence Sampler/RWM MCMC Adaptation
#' @description 
#' Adapts proposal parameters of INdependence Sampler/RWM MCMC scheme
#' to give near-optimal performance.
#' @param init initial value of epidemic parameters
#' @param U_init initial value of random variables used to construct
#'               epidemic trajectory.
#' @param epiModel epidemic model
#' @param obsFrame Generator function for observational model.
#' @param epiSample Observed epidemic data.
#' @param I0 Initial state of the epidemic, which assumed to be known.
#' @param alpha Observational parameters to be passed on to the log-likelihood function
#'              generated by `obsFrame(X_sim)`
#' @param logPrior Functions which calculate log-density of the assumed priors of the 
#'                 epidemic parameters.
#' @param lambda0  Initial value of the Random Walk Metropolis (RWM) proposal scale parameter
#' @param V0 A square matrix containing the initial covariance values for RWM proposal. Shape
#'           of matrix should match the length of the init parameter.
#' @param S0 Initial number of non-centered random variables to be 'refreshed' in Independence
#'           Sampler proposal step.
#' @param noIts Number of iterations of MCMC sampler scheme to carry out.
#' @param delta Probability that the initial proposal parameters are used as opposed to using 
#'              the current adapted proposal parameters.
#' @return 
#' A list of the adapted proposal parameters.
#' 
#' @export

adapt_ISMCMC <- function(init, U_init, epiModel, obsFrame, epiSample, I0, alpha, logPrior, 
                         lambda0, V0, S0, noIts, delta = 0.05){
  # Set up functions
  k <- length(init)
  r <- length(U_init)
  # Estimate Likelihood for initial parameters
  epi_init <- epiModel$sim(list(I0, init, U_init))
  obsModelInit <- obsFrame(epi_init)
  logLikeCurr <- obsModel$llh(epiSample, alpha)
  while(is.infinite(logLikeCurr)){
    U_init <- matrix(runif(r, 0, 1), ncol = ncol(U_init), nrow = nrow(U_init))
    epi_init <- epiModel$sim(list(I0, init, U_init))
    obsModelInit <- obsFrame(epi_init)
    logLikeCurr <- obsModelInit$llh(epiSample, alpha)
  }
  curr <- init
  U_curr <- U_init
  epi_curr <- epi_init
  obsModelCurr <- obsModelInit
  
  S <- S0
  lambda <- lambda0
  
  accept <- 0
  draws <- matrix(ncol = k + 1, nrow = noIts)
  for(i in 1:noIts){
    adapt <- accept > 10 & (runif(1, 0, 1) > delta)
    
    # Propose new epidemic parameters
    if(adapt){
      V <- var(draws[1:(i-1), 1:k])
      prop <- abs(curr + mvnfast::rmvn(1, mu = rep(0, k), sigma = lambda*V))
    } else{
      prop <- abs(curr + mvtnorm::rmvnorm(1, mean = rep(0, k), sigma = lambda0*V0))
    }

    # Estimate Likelihood
    epiProp <- epiModel$sim(list(I0, prop, U_curr))
    obsModelProp <- obsFrame(epiProp)
    logLikeProp <- obsModelProp$llh(epiSample, alpha)

    
    if(!is.infinite(logLikeProp)){
      logAccProb <- (logLikeProp + logPrior(prop)) - (logLikeCurr + logPrior(curr)) 
      #print(logAccPRob)
      if(log(runif(1, 0, 1)) < logAccProb){
        curr <- prop
        logLikeCurr <- logLikeProp 
        accept <- accept + 1
        if(adapt){
          lambda <- lambda + 3*(lambda/i^(1/3))
        } 
      } else{
        if(adapt){
          lambda <- lambda - 1*(lambda/i^(1/3))
        }
      }
    }
    

    # Propose new epidemic parameters
    if(adapt){
      U_prop <- U_curr
      U_prop[sample(1:r, S, replace = F)] <- runif(S, 0, 1)
    } else{
      U_prop <- U_curr
      U_prop[sample(1:r, S0, replace = F)] <- runif(S0, 0, 1)
    }
    
    # Estimate Likelihood
    epiProp <- epiModel$sim(list(I0, curr, U_prop))
    obsModelProp <- obsFrame(epiProp)
    logLikeProp <- obsModelProp$llh(epiSample, alpha)
    
    
    if(!is.infinite(logLikeProp)){
      logAccProb <- (logLikeProp + logPrior(prop)) - (logLikeCurr + logPrior(curr)) 
      #print(logAccPRob)
      if(log(runif(1, 0, 1)) < logAccProb){
        U_curr <- U_prop
        logLikeCurr <- logLikeProp 
        accept <- accept + 1
        if(adapt){
          S <- S + rbinom(1, 3, prob = 0.75/sqrt(i))
          #ceiling(0.75*(S/sqrt(i)))
          if(S > r){
            S <- r
          }
        } 
      } else{
        if(adapt){
          S <- S - rbinom(1, 1, prob = 0.25/sqrt(i))
          #ceiling(0.25*(S/sqrt(i)))
          if(S < 1){
            S <- 1
          }
        }
      }
    }
    draws[i, ] <- c(curr, logLikeCurr)
  }
  return(list(lambda = lambda, V = var(draws[,1:k]), S = S))
}