#' Generate a function which calculates Monte Carlo estimate of Epidemic sample Likelihood 
#' given a set of epidemic parameters. 
#' @param sample   An observation of an SIR epidemic with a metapopulation
#'                 structure. The format of this object must be the same 
#'                 as the format which is returned from `obsModel$sample()`,
#'                 where obsModel is generated by `obsFrame`.
#' @param epiModel Epidemic model with simulator and likelihood functions.
#'                 A representation of how the real-world epidemic is assumed
#'                 to behave.
#' @param obsFrame Function which generates the observation model given an epidemic. 
#'                 A representation of how a realisation of an epidemic, described
#'                 by `epiModel`, is assumed to be observed.
IS <- function(y, obsFrame, epiModel, parallel = F){
  sample_w <- function(param){
    alpha <- param[[3]]
    # EpiParam Structure Check
    # type_check <- typeof(epiParam) == epiModel$param_dim$type
    # dim_check <- prod(sapply(X = 1:length(epiParam), 
    #                         function(X) length(epiParam[[X]]) == epiModel$param_dim$dims[[X]]))
    # if(!type_check | !type_check){
    #   stop("Check Epidemic Parameter Structure!")
    # }
    param <- list(param[[1]], param[[2]])
    
    X <- epiModel$sim(param)
    obsModel <- obsFrame(X)
    logw <- obsModel$llh(y, alpha)
    return(logw)
  }
  
  # ESS <- function(log_weights){
  #   
  # }
  
  est <- function(N, param){
    logw <- replicate(n = N, sample_w(param))
    
    #est <-  lapply(X = func, FUN = function(X) return(X(w)))
    est <- log_mean_exp(logw)
    #w <- exp(logw)
    #w_norm <- w/sum(w)
    #ESS <- 1/(w_norm)^2
    
    return(list(estimates = est, log_weights = logw))
  }

  # if(parallel){
  #   est <- function(N, param){
  #     registerDoParallel(parallel::detectCores() - 1)
  #     llh <- foreach(i = 1:N, .combine = c) %dopar%{
  #       sample_llh(param)
  #     }
  #     log_est <- log_sum_exp(llh)
  #     #log_est <- log(mean(exp(llh)))
  #     return(log_est)
  #   }
  # } else{
  #   est <- function(N, param){
  #     llh <- replicate(n = N, sample_llh(param))
  #     log_est <- log_sum_exp(llh)
  #     #log_est <- log(mean(exp(llh)))
  #     return(log_est)
  #   }
  # }

  return(est)
}


